### PR TITLE
Added Font Picker

### PR DESCRIPTION
**Pull request by Zangoran**
Used a library for the picker, which was worked into the extension. It adds the ability to select a font from many of the google fonts. It also remembers the font that is selected.

### CODE REVIEW

**Comment by bluecaret** [comment]
Thank you! I'll take a look through this when I get some time. Please be patient in the meantime. :)

**Comment by Zangoran** [comment]
@bluecaret Awesome, thanks!

**Comment by bluecaret** [comment]
Hi @Zangoran I like your solution. However I won't be merging in with the main branch, this is a feature that I need to add with extra care. For one thing, the full list of google fonts should be an optional choice, alongside the set list I had originally. The set list allows the extension to fully work offline, whereas the Google Font list would require a connection as well as possibly slowing down opening a new tab as it pulls from Google's server to load the font.

I'm currently working on a complete overhaul of this extension separate from this Github repo that once I'm done will be merged in here. I'll definitely be including your work within this overhaul, but this means you won't see this PR merged, but no worries it will be used :) 

Thank you very much for your assistance!

**Comment by bluecaret** [comment]
Thank you for this again, I have decided to go with an option of allowing the user to enter the name of any locally installed fonts on their system with a link to google fonts if they want to find more to download. I felt this warranted the best performance for the extension and keeps it working offline. Thank you.

**Comment by Zangoran** [comment]
@bluecaret That is a great idea, I like it. Thanks!

**Pull request closed without merging**
