### PR TITLE
Fixes #5

### LINKED ISSUE #5: Text on Tab
As suggested by Tanmay Kumar via Chrome Store:

> The text on the tab currently shows the time. eg. 11:08:06 PM, it would be great if it showed something like "New Tab" or even better allowed to customize it. And the extension is great!

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
This fixes #5, i can make it configurable if you wish that. 
Great extension!

### CODE REVIEW

**Comment by bluecaret** [comment]
Hi, thanks for the help! I had plans to make this configurable. The idea was to have it act the following way:

- add toggle in extra settings called "Tab Title" with the following options:
-- Use Time (Should follow the same options as main time display for meridian and delimiters and military)
-- Use "New Tab"
-- Use the Custom Message text (if empty default to "New Tab")

If you want to give this a shot to add that would be helpful, otherwise ill be having some time myself to work on the extension in a week or so at which point I'll work on this myself.

Thank you and thanks for the support!

**Comment by bil-elmoussaoui** [comment]
Will implement this tomorrow evening! :)

**Comment by bil-elmoussaoui** [comment]
Update the commit, here's some screenshots 
capture d ecran de 2016-11-24 16-27-29
capture d ecran de 2016-11-24 16-27-32
capture d ecran de 2016-11-24 16-27-34
capture d ecran de 2016-11-24 16-27-39

**Comment by bluecaret** [comment]
Thanks! Looking good! Couple bugs though. 

- When setting to use the time, the time is not auto updated per second on the tab.
- When setting to use the time, changing time settings to hide/show seconds, meridian, etc, does not update the display in the tab.
- Let's change it from saying "Use custom message text" to just "Use Custom Text".
- Would you mind adding another option in that to use the date? So would say "Use Date"? Also make sure it updates automatically.
- Double check that if time is not displayed in the tab, and time is not displayed in the page, that the code is not updating the time at all to save on resources.

Note to myself (unless your good with CSS as well, keep in mind I'm using LESS), need to add styling to text boxes if it is disabled.

If you want to do these changes that would be awesome, otherwise next week I can get to it. Either way I'll update the extension next week with this feature! Thanks again for the help!

**Comment by bil-elmoussaoui** [comment]
I will fix all the mentioned issues tomorrow evening

**Comment by bil-elmoussaoui** [comment]
I totally forgot about updating this! And as you've merged it already, can you take care of the rest? as i'm so busy those days with other projects..

**Comment by bluecaret** [comment]
No problem! I'm thankful for the work you already put in. Yes, I'm working on finishing this right now. Thanks!

**Comment by bluecaret** [comment]
@bil-elmoussaoui thanks again for your help, just letting you know this has been pushed out and updated on the chrome store now!

**Pull request merged**
