### PR TITLE
Fr translation review part one

### PR DESCRIPTION
**Pull request by Moosh-be**
Some corrections in french translation.

(I do it in many passes because I do it when I found where it's used)

### CODE REVIEW

**Comment by bluecaret** [comment]
Thank you very much for this help! Let me know when you are done going through it and I'll get this approved.

**Comment by Moosh-be** [comment]
@bluecaret  For translation fixes, I take great care not to "break" the json syntax but I don't have a way to "compile" to retest

Personally I prefer to make several PR containing several corrections.

I prefer one fix per commit, but multiple fixes in a single PR.

And do several PRs as I go through my correction sessions (I'm pretty erratic because I do this for every product I use).

So you can approve whenever you want and I will start a new PR if I find other improvements to do.

**Comment by bluecaret** [comment]
That sounds good. And with translation fixes, no need to compile to test, I'll do so before publishing. I'll take whatever I can get with translations :)

**Comment by Moosh-be** [comment]
I'm ready

**Pull request merged**
